#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --config $HOME/.config/picom/picom.conf &

feh --bg-scale $HOME/ArchAutopwm/wallpaper/lainwallpaper2.jpg &

polybar -c $HOME/.config/polybar/forest/config.ini &
bash $HOME/.config/polybar/forest/launch.sh &

exec bspwm
